spring:
  cloud:
    openservicebroker:
      catalog:
        services:
        - id: d897c845-e15e-467e-9c34-71632e8807e1
          name: route-service
#          description: Rate-limiting and logging route service
          description: Rate-limiting route service based on user role
          bindable: true
          requires: ["route_forwarding"]
          tags:
          - route-service
          - logging
          metadata: # optional
            #imageUrl: https://static-content.cfapps.io/images/service-broker-icon.png
            imageUrl: https://${vcap.application.uris[0]}/images/service-broker-icon.png
            displayName: A S1P Demo Gateway Service
            longDescription: Spring Cloud Gateway service, intended to be bound as a route service.
            documentationUrl: https://docs.cloudfoundry.org/devguide/services/route-binding.html
            providerDisplayName: Pivotal
          plans:
          - id: 3944a61c-ed68-45c5-b649-a99d1f301c69
            name: standard
            description: standard plan
            free: true
            bindable: true
            metadata:
              displayName: Rate Limiter (Trial, Basic, and Premium)
#          - id: 3944a61c-ed68-45c5-b649-a99d1f301c69
#            name: trial
#            description: trial plan
#            free: true
#            bindable: true
#            metadata:
#              displayName: Trial (3 requests/sec, 3 burst capacity)
##              bullets: ["3 request per second", "3 request burst capacity"]
#          - id: 3944a61c-ed68-45c5-b649-a99d1f301c70
#            name: standard
#            description: standard plan
#            free: true
#            bindable: true
#            metadata:
#              displayName: Standard (10 requests/sec, 15 burst capacity)
##              bullets: ["10 request per second", "15 request burst capacity"]
##              costs:
##              - amount:
##                  usd: 10
##                unit: MONTHLY
#          - id: 3944a61c-ed68-45c5-b649-a99d1f301c71
#            name: premium
#            description: premium plan
#            free: true
#            bindable: true
#            metadata:
#              displayName: Premium (30 requests/sec, 100 burst capacity)
##             bullets: ["50 request per second", "100 request burst capacity"]
##              costs:
##              - amount:
##                  usd: 40
##                unit: MONTHLY

management:
  endpoints:
    web:
      exposure:
        include: "*"

#servicecatalogconfig:
#      services:
#      - id: d897c845-e15e-467e-9c34-71632e8807e1
#        plans:
#        - id: 3944a61c-ed68-45c5-b649-a99d1f301c69
#          replenishRate: 3
#          burstCapacity: 3
#        - id: 3944a61c-ed68-45c5-b649-a99d1f301c70
#          replenishRate: 10
#          burstCapacity: 15
#        - id: 3944a61c-ed68-45c5-b649-a99d1f301c71
#          replenishRate: 50
#          burstCapacity: 100

servicecatalogconfig:
  services:
  - id: d897c845-e15e-467e-9c34-71632e8807e1
    plans:
    - id: 3944a61c-ed68-45c5-b649-a99d1f301c69
      trialReplenishRate: 3
      trialBurstCapacity: 3
      basicReplenishRate: 10
      basicBurstCapacity: 15
      premiumReplenishRate: 50
      premiumBurstCapacity: 100
